config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'items#index'

  resources :items do
    member do
      get :buy
      post :pay
      get :purchase
      get :look
    end
  end

  resources :users do
    member do
      get :signout
      get :listing
    end
  end

  resources :credits do
    collection do
      get 'index'
      get 'complete', to: 'credits#complete'
      post 'payment', to: 'credits#payment'
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_many :credits
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname,:email,:telephone,:birth_year,:birth_month,:birth_day,presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  prepend_before_filter :verify_user, only: [:destroy]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user,only:[:show,:signout,:listing,:edit]
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def signout
  end

  def listing
    @items = Item.where(user_id: current_user.id)
  end

  private

  def set_user
    @user = current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.main_header
  = render 'shared/header'
  / - breadcrumb :user
  / = breadcrumbs pretext: " ", separator: " › "
%section.pickup-container
  .mypage-body.clearfix
    = render 'shared/user-side'
    .main__content
      %section.l-chapter-container
        %h2.l-chapter-head
          本人情報の登録
        .l-single-inner
          = form_for(current_user) do |f|
            .text
              %p
                お客さまの本人情報をご登録ください。
                %br>/
                登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
              %p.text-right
                = link_to '本人確認書類のアップロードについて＞', 'https://www.mercari.com/jp/help_center/article/495/'

            .form-group
              =f.label :お名前
              %span.form-require 必須
              = f.text_field :family_name_kanji, class: "input__default", placeholder: "例）横倉"
              = f.text_field :first_name_kanji, class: "input__default", placeholder: "例）達也"

            .form-group
              =f.label :お名前カナ
              %span.form-require 必須
              = f.text_field :family_name_kana, class: "input__default", placeholder: "例）ヨコクラ"
              = f.text_field :first_name_kana, class: "input__default", placeholder: "例）タツヤ"

            .form-group
              =f.label :生年月日
              %span.form-require 必須
              %br>/
              .birth-select-wrap
                .select-wrap
                  .select-box
                    = f.select :birth_year,[*(1900..2018)]
                %p
                  年
                .select-wrap
                  .select-box
                    = f.select :birth_month,[*(1..12)]
                %p
                  月
                .select-wrap
                  .select-box
                    = f.select :birth_day,[*(1..31)]
                %p
                  日
              %p.form-info-text ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
              .clearfix

            .form-group
              =f.label :郵便番号
              %span.form-arbitrary 任意
              = f.text_field :zip_code, class: "input__default", placeholder: "例）1500043"

            .form-group
              =f.label :都道府県
              %span.form-arbitrary 任意
              %br>/
              .prefecture-select-wrap
                .select-wrap
                  .select-box
                    = f.select :prefecture, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","東京都","神奈川県","埼玉県","千葉県","茨城県","栃木県","群馬県","山梨県","新潟県","長野県","富山県","石川県","福井県","愛知県","岐阜県","静岡県","三重県","大阪府","兵庫県","京都府","滋賀県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"]
              .clearfix
            .form-group
              =f.label :市町村
              %span.form-arbitrary 任意
              = f.text_field :city, class: "input__default", placeholder: "例）横浜市緑区"

            .form-group
              =f.label :番地
              %span.form-arbitrary 任意
              = f.text_field :address1, class: "input__default", placeholder: "例）道玄坂1-1-1"

            .form-group
              =f.label :建物名
              %span.form-arbitrary 任意
              = f.text_field :address2, class: "input__default", placeholder: "例）フォンティスビル701"

              .update-box
                = f.submit "登録する", class:"update-box-btn"
              .info-text-right
                %p
                  = link_to '本人情報の登録について＞','https://www.mercari.com/jp/help_center/article/423/'

= render 'shared/footer'
= render 'shared/sell-button'

app/views/users/listing.html.haml
.main_header
  = render 'shared/header'
%section.pickup-container

  .mypage-body.clearfix
    = render 'shared/user-side'
    .main__content
      .tabs
        %input#notice{:checked => "checked", :name => "tab_user", :type => "radio"}/
        %label.tab_user{:for => "notice"}
          出品中
        %input#todo{:name => "tab_user", :type => "radio"}/
        %label.tab_user{:for => "todo"}
          売却済み
        #notice_content.tab_content
          %ul.tab-content
            %li.notice_content
              - @items.each do |item|
                = link_to look_item_path(id: item.id) , class: "tab-content__list"  do
                  = image_tag item.item_images[0].image, class: "tab-content__list--mercari"
                  = fa_icon "angle-right", class: "tab-content__list--arrow"
                  .tab-content__list--body
                    .tab-content__list--body-text
                      = item.name
        #todo_content.tab_content
          = image_tag("user-joukyo.png" , class: "tab-content__list--picture" )

app/views/users/show.html.haml
.main_header
  = render 'shared/header'
  - breadcrumb :user
  = breadcrumbs pretext: " ", separator: " › "
%section.pickup-container
  .mypage-body.clearfix
    = render 'shared/user-side'
    .main__content
      %section.user-information
        =link_to "#" , class: "user-information__link" do
          .user-information__figure
            = image_tag('https://static.mercdn.net/members/470676864.jpg?1500122515', size: "60" , class: "user-information__figure--icon")
            %h3.user-information__name
              = @user.nickname
            .user-information__number
              .user-information__number--review
                評価
                %span.bold
                  7
              .user-information__number--exhibit
                出品数
                %span.bold
                  30
      .user-information__tab
        //タブの開始
        .tabs
          %input#notice{:checked => "checked", :name => "tab_user", :type => "radio"}/
          %label.tab_user{:for => "notice"}
            お知らせ
          %input#todo{:name => "tab_user", :type => "radio"}/
          %label.tab_user{:for => "todo"}
            やることリスト
          #notice_content.tab_content
            //タブ-リストの開始
            %ul.tab-content
              %li.notice_content
                = render 'shared/user-tab'
            //タブ-リスト（やることリスト）
          #todo_content.tab_content
            %ul.tab-content
              %li.todo_content
                = image_tag("https://www.mercari.com/jp/assets/img/common/common/logo-gray-icon.svg?62593201" , class: "tab-content__list--image" )
                .text 現在、やることリストはありません
      //ユーザーの商品情報（下の部分）
      %section.trade-information
        %h2.trade-information__tab
          購入した商品
        //タブの部分
        .tabs
          %input#trade-now{:checked => "checked", :name => "tab_item", :type => "radio"}/
          %label.tab_user{:for => "trade-now"}
            取引中
          %input#trade-kako{:name => "tab_item", :type => "radio"}/
          %label.tab_item{:for => "trade-kako"}
            過去の取引
          #trade-now_content.tab_content
            %ul.trade-now-content
              %li.trade-now_content
                = render 'shared/user-tab'
          #trade-kako_content.tab_content
            = image_tag("https://www.mercari.com/jp/assets/img/common/common/logo-gray-icon.svg?62593201" , class: "tab-content__list--image" )
            .text 過去の取引はございません

  = render 'shared/footer'
  = render 'shared/sell-button'

app/views/users/signout.html.haml
.main_header
  = render 'shared/header'
  //ページのルート表示
  - breadcrumb :user_signout
  = breadcrumbs pretext: " ", separator: " › "
  //ユーザーサイトのメイン部分
%section.pickup-container
  .mypage-body.clearfix
    //左のメニュー部分
    = render 'shared/user-side'
    //右のコンテンツ
    .main__content
      .signout__content
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "signout__content--button"
  = render 'shared/footer'
  = render 'shared/sell-button'