config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'items#index'

  resources :items do
    member do
      get :buy
      post :pay
      get :purchase
      get :look
    end
  end

  resources :users do
    member do
      get :signout
      get :listing
    end
  end

  resources :credits do
    collection do
      get 'index'
      get 'complete', to: 'credits#complete'
      post 'payment', to: 'credits#payment'
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
end

app/views/shared/_body.html.haml
%h2.pickup-head
  ピックアップカテゴリー
  %h3.items__pickup__container
    = link_to "" ,class: "items__pickup__container__category" do
      = "#{@category1.name} 新着アイテム"
  %section.item-boxs.clearfix
    -@items.each do |item|
      %li.item-box
        = link_to "/items/#{item.id}" do
          %figure.item-box__figure
            / 商品の一枚目の写真を表示
            = image_tag item.item_images[0].image, alt: "",class: "item-box__image"
          .item-box__body
            .item-box__text
              .item-box__name
                =item.name
            .item-box__num
              .item-box__num__price
                = number_to_currency( "#{item.price}", locale: 'jp')
                .nice
                  = fa_icon "heart", type: :regular, class: "icon-like-border"
                  %span
                    1
              %p.item-box__num__price-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", root_path
  %h3.items__pickup__container
    = link_to "" ,class: "items__pickup__container__category" do
      = "#{@category2.name} 新着アイテム"
  %section.item-boxs.clearfix
    -@items.each do |item|
      %li.item-box
        = link_to "/items/#{item.id}" do
          %figure.item-box__figure
            / 商品の一枚目の写真を表示
            = image_tag item.item_images[0].image, alt: "",class: "item-box__image"
          .item-box__body
            .item-box__text
              .item-box__name
                =item.name
            .item-box__num
              .item-box__num__price
                = number_to_currency( "#{item.price}", locale: 'jp')
                .nice
                  = fa_icon "heart", type: :regular, class: "icon-like-border"
                  %span
                    1
              %p.item-box__num__price-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", root_path
  %h3.items__pickup__container
    = link_to "" ,class: "items__pickup__container__category" do
      = "#{@category3.name} 新着アイテム"
  %section.item-boxs.clearfix
    -@items.each do |item|
      %li.item-box
        = link_to "/items/#{item.id}" do
          %figure.item-box__figure
            / 商品の一枚目の写真を表示
            = image_tag item.item_images[0].image, alt: "",class: "item-box__image"
          .item-box__body
            .item-box__text
              .item-box__name
                =item.name
            .item-box__num
              .item-box__num__price
                = number_to_currency( "#{item.price}", locale: 'jp')
                .nice
                  = fa_icon "heart", type: :regular, class: "icon-like-border"
                  %span
                    1
              %p.item-box__num__price-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", root_path
%h2.pickup-head
  ピックアップブランド
  %h3.items__pickup__container
    = link_to "" ,class: "items__pickup__container__category" do
      = "#{@brand1.name} 新着アイテム"
  %section.item-boxs.clearfix
    -@items.each do |item|
      %li.item-box
        = link_to "/items/#{item.id}" do
          %figure.item-box__figure
            / 商品の一枚目の写真を表示
            = image_tag item.item_images[0].image, alt: "",class: "item-box__image"
          .item-box__body
            .item-box__text
              .item-box__name
                =item.name
            .item-box__num
              .item-box__num__price
                = number_to_currency( "#{item.price}", locale: 'jp')
                .nice
                  = fa_icon "heart", type: :regular, class: "icon-like-border"
                  %span
                    1
              %p.item-box__num__price-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", root_path

app/views/shared/_credit.html.haml
.signup__inner
  .signup__inner__container
    .signup__inner__group
      = form_tag(pay_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
        .pay-input
          %label.text カード番号
          %span.form 必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.pay-input_img
            %li.pay
              = image_tag("visa.svg", class: "card--image", width: "49")
            %li.pay
              = image_tag("master-card.svg", class: "card--image", width: "34")
            %li.pay
              = image_tag("saison-card.svg", class: "card--image", width: "30")
            %li.pay
              = image_tag("jcb.svg", class: "card--image", width: "32")
            %li.pay
              = image_tag("american_express.svg", class: "card--image", width: "21")
            %li.pay
              = image_tag("dinersclub.svg", class: "card--image", width: "32")
            %li.pay
              = image_tag("discover.svg", class: "card--image", width: "32")
        .pay-num
          %label.text-limit 有効期限
          %span.form 必須
          %br
          %select#exp_month{name: "exp_month", type: "text"}
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
          / %i.fas.fa-chevron-down
          .expire-month 月
          %select#exp_year{name: "exp_year", type: "text"}
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          .expire-year 年
          / %i.fas.fa-chevron-down
        .pay-code
          %label.text セキュリティコード
          %span.form 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁番号", maxlength: "4", id: "cvc"
          .pay-code_text
            ?
          %span.card
            カード裏面の番号とは？
          #card_token
          = submit_tag "追加する",class: "btn-default btn-red", id: "token_submit"

app/views/shared/_edit_tab.haml
%ul.tab-content
  %li.notice_content
    - @items.each do |item|
      = link_to item_check_path(id: item.id) , class: "tab-content__list"  do
        = image_tag item.item_images[0].image, class: "tab-content__list--mercari"
        = fa_icon "angle-right", class: "tab-content__list--arrow"
        .tab-content__list--body
          .tab-content__list--body-text
            = item.name

app/views/shared/_footer-logo.html.haml
%footer.user__container__footer
  %nav
    %ul.user__footer__nav
      %li プライバシーポリシー
      %li メルカリ利用規約
      %li 特定商取引に関する表記
  = link_to "/", class: "user__footer__logo" do
    = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?613028459", alt: "mercari-gray", class: "user__footer__logo-gray", width: "80", height: "65")
  %p.user__footer__info
    %small ©︎ 2019 Mercari

app/views/shared/_footer.html.haml
%aside.app-banner
  .app-banner-pc
    .app-banner-pc-inner
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner-icon.clearfix
        %figure
          = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?1313722577', width: 68
        %ul.clearfix
          %li
            = link_to 'https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8', target: '_blank' do
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?1313722577', width: 133 ,height: 40
          %li
            = link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', target: '_blank' do
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?1313722577', width: 133 ,height: 40
    %figure
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?1313722577'
%footer.global-footer
  %nav.clearfix
    .footer-cell
      %h2.footer-head
        メルカリについて
      %ul
        %li
          = link_to "会社概要（運営会社）"
        %li
          = link_to "採用情報"
        %li
          = link_to "プレスリリース"
        %li
          = link_to "公式ブログ"
        %li
          = link_to "メルカリロゴ利用ガイドライン"
        %li.footer-social-link
          = link_to do
            %i.fab.fa-twitter
        %li.footer-social-link
          = link_to do
            %i.fab.fa-facebook
    .footer-cell
      %h2.footer-head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "メルカリガイド"
        %li
          = link_to "らくらくメルカリ便"
        %li
          = link_to "ゆうゆうメルカリ便"
        %li
          = link_to "大型メルカリ便"
        %li
          = link_to "車体取引ガイド"
        %li
          = link_to "メルカリあんしん・あんぜん宣言！"
        %li
          = link_to "偽ブランド品撲滅への取り組み"
        %li
          = link_to "メルカリボックス"
    .footer-cell.full-width
      %h2.footer-head プライバシーと利用規約
      .inner-footer-cell
        %ul
          %li
            = link_to "プライバシーポリシー"
          %li
            = link_to "メルカリ利用規約"
          %li
            = link_to "メルカリ利用規約・有償ポイントに関する特約"
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約"
          %li
            = link_to "コンプライアンスポリシー"
      .inner-footer-cell-left
        %ul
          %li
            = link_to "個人データの安全管理に係る基本方針"
          %li
            = link_to "特定商取引に関する表記"
          %li
            = link_to "資金決済法に基づく表示"
          %li
            = link_to "法令順守と犯罪抑止のために"
          %li
            = link_to "返品・返金ポリシー"
    .footer-cell.footer-nav-lang
      %h2.footer-head 国
      %ul
        %li
          = link_to "日本"
        %li
          = link_to "United States"
  .footer-bottom
    .footer-logo
      = link_to do
        = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?3112359103', width: 124, height: 33
    %span.footer-copyright
      %small © 2019 Mercari

app/views/shared/_header-logo.html.haml
%header.user__container__header
  %h1
    = link_to "/" do
      = image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?613028459", alt: "mercari", width: "185", height: "49")

app/views/shared/_header.html.haml
.header
  .header_top.clearfix
    .header_top__title
      = link_to root_path, class: 'header_top__title--logo' do
        = image_tag('https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1016580576', :class => "mercari_logo")
    .header_top__form
      .header_top__form--input-box
        = form_tag( 'search_articles_path', method: :get ) do
          = text_field_tag :q, '', class: 'header_top__form--input-box__text',placeholder: '何かお探しですか？'
        = link_to root_path, class: 'header_top__form--input-box__btn' do
          = fa_icon "search"
  .header-nav.clearfix
    %ul.header-nav-left
      %li.header-nav-left__category
        %h2
          = fa_icon "list-ul"
          = link_to 'カテゴリーから探す', "#"
        %ul.header-nav-left__brand__wrap
          %li
            %h3
              = link_to 'レディース', "#"
            %ul
              %li
                = link_to 'トップス', "#"
                %ul
                  %li
                    = link_to 'Tシャツ/カットソー(半袖/袖なし)', "#"
                  %li
                    = link_to 'Tシャツ/カットソー(七分/長袖)', "#"
                  %li
                    = link_to 'シャツ/ブラウス(半袖/袖なし)', "#"
                  %li
                    = link_to 'シャツ/ブラウス(七分/長袖)', "#"
                  %li
                    = link_to 'ポロシャツ', "#"
                  %li
                    = link_to 'キャミソール', "#"
                  %li
                    = link_to 'タンクトップ', "#"
                  %li
                    = link_to 'ホルターネック', "#"
                  %li
                    = link_to 'ニット/セーター', "#"
                  %li
                    = link_to 'チュニック', "#"
                  %li
                    = link_to 'カーディガン/ボレロ', "#"
                  %li
                    = link_to 'アンサンブル', "#"
                  %li
                    = link_to 'ベスト/ジレ', "#"
                  %li
                    = link_to 'パーカー', "#"

          %li
            %h3
              = link_to 'メンズ', "#"
          %li
            %h3
              = link_to 'ベビー・キッズ', "#"
          %li
            %h3
              = link_to 'インテリア・住まい・小物', "#"
          %li
            %h3
              = link_to '本・音楽・ゲーム', "#"
          %li
            %h3
              = link_to 'おもちゃ・ホビー・グッズ', "#"
          %li
            %h3
              = link_to 'コスメ・香水・美容', "#"
          %li
            %h3
              = link_to '家電・スマホ・カメラ', "#"
          %li
            %h3
              = link_to 'スポーツ・レジャー', "#"
          %li
            %h3
              = link_to 'ハンドメイド', "#"
          %li
            %h3
              = link_to 'チケット', "#"
          %li
            %h3
              = link_to '自動車・オートバイ', "#"
          %li
            %h3
              = link_to 'その他', "#"
          %li
            %h3
              = link_to 'カテゴリー一覧', "#"

      %li.header-nav-left__brand
        %h2
          = fa_icon "tag"
          = link_to 'ブランドから探す', "#"
        %ul.header-nav-left__brand__wrap
          %li
            %h3
              = link_to 'シャネル', "#"
          %li
            %h3
              = link_to 'ナイキ', "#"
          %li
            %h3
              = link_to 'ルイ ヴィトン', "#"
          %li
            %h3
              = link_to 'シュプリーム', "#"
          %li
            %h3
              = link_to 'アディダス', "#"
          %li
            %h3
              = link_to 'ブランド一覧', "#"

    %ul.header-nav-user
      - if user_signed_in?
        %li.header-nav-user--news
          %i.far.fa-bell
            = link_to 'お知らせ'
        %li.header-nav-user--todo
          %i.fas.fa-check
            = link_to 'やることリスト'
        %li.header-nav-use--mypage
          = link_to user_path(id: current_user.id) do
            %figure
              = image_tag 'https://static.mercdn.net/members/470676864.jpg?1500122515'
              マイページ
      - else
        %ul.header-nav-right
          %li.header-nav-right__login
            = link_to 'ログイン', new_user_session_path
          %li.header-nav-right__signup
            = link_to '新規会員登録', new_user_registration_path

app/views/shared/_login-footer.html.haml
.main-content__footer
  .main-content__footer-list
    .main-content__footer-list-privacy-policy
      = link_to 'プライバシーポリシー','https://www.mercari.com/jp/privacy/',class: 'privacy'
    .main-content__footer-list-agreement
      = link_to 'メルカリ利用規約','https://www.mercari.com/jp/tos/',class: 'agreement'
    .main-content__footer-list-tokutei
      = link_to '特定商取引に関する表記','https://www.mercari.com/jp/tokutei/',class:'tokutei'
  .mercari-footer
    .mercari-logo
      = link_to root_path do
        = image_tag'https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?128691313'
  .mercari--under-logo © 2019 Mercari

app/views/shared/_mercari-header.haml
%header
  %h1
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?454567723"

app/views/shared/_sell-button.html.haml
.footer-sell-btn
  = link_to new_item_path do
    %div 出品
    %i.fas.fa-camera

app/views/shared/_top-carousel.html.haml
.top-carousel
  #owl-example.owl-carousel.owl-theme
    .new-life
      = image_tag "top-carousel.newlife.png", :alt => "メルカリでかしこくおトクに新生活をはじめよう！"
    .main
      = image_tag "top-carousel.main.png", :alt => "スマホでかんたん フリマアプリ"
    .bokuranoheisei
      = image_tag "top-carousel.bokuranoheisei.png", :alt => "僕らの平成30年史 往年の名作はメルカリで。"
  .owl-prev
  .owl-next

app/views/shared/_user-header.haml
%header
  %h1
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?454567723"

app/views/shared/_user-side.html.haml
.side__content
  %nav.mypage-nav
    %ul.mypage-nav__list
      = link_to user_path(id: current_user.id) do
        .mypage-nav__list--item
          マイページ
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          お知らせ
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          やることリスト
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          いいね一覧
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to new_item_path do
        .mypage-nav__list--item
          出品する
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to listing_user_path (@user.id) do
        .mypage-nav__list--item
          出品した商品-出品中
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
        .mypage-nav__list--item
          出品した商品-取引中
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
        .mypage-nav__list--item
          出品した商品-売却済み
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
        .mypage-nav__list--item
          購入した商品-取引中
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          購入した商品-過去の取引
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          ニュース一覧
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          評価一覧
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          ガイド
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          お問い合わせ
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
    %h3.mypage-nav__head
      メルペイ
    %ul.mypage-nav__list
      = link_to "" do
        .mypage-nav__list--item
          売上・振込申請
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          ポイント
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
    %h3.mypage-nav__head
      設定
    %ul.mypage-nav__list
      = link_to edit_user_path (@user.id) do
        .mypage-nav__list--item
          プロフィール
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          住所変更
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to credits_path do
        .mypage-nav__list--item
          支払い方法
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "" do
        .mypage-nav__list--item
          メール/パスワード
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to edit_user_path (@user.id) do
        .mypage-nav__list--item
          本人情報
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to edit_user_path (@user.id) do
        .mypage-nav__list--item
          電話番号の確認
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"
      = link_to "/users/#{current_user.id}/signout" do
        .mypage-nav__list--item
          ログアウト
          = fa_icon "angle-right", class: "mypage-nav__list--arrow"

app/views/shared/_user-tab.html.haml
= link_to "" , class: "tab-content__list"  do
  = image_tag("https://static.mercdn.net/images/mercari_profile.png", class: "tab-content__list--mercari")
  = fa_icon "angle-right", class: "tab-content__list--arrow"
  .tab-content__list--body
    .tab-content__list--body-text
      明日、5%還元お得チケットの有効期限が切れます！タップして詳細を確認しましょう。
    .tab-content__list--body-time
      = fa_icon "clock-o", class: "tab-content__icon--time"
      %span
        57分前
= link_to "" , class: "tab-content__list"  do
  = image_tag("https://static.mercdn.net/images/mercari_profile.png", width: "48", class: "tab-content__list--mercari")
  = fa_icon "angle-right", class: "tab-content__list--arrow"
  .tab-content__list--body
    .tab-content__list--body-text
      お出かけ中の人はぜひ！いまならセブンカフェが¥11になるクーポン配信中！利用は5/31まで
    .tab-content__list--body-time
      = fa_icon "clock-o", class: "tab-content__icon--time"
      %span
        5時間前
= link_to "" , class: "tab-content__list"  do
  = image_tag("https://static.mercdn.net/images/mercari_profile.png", width: "48", class: "tab-content__list--mercari")
  = fa_icon "angle-right", class: "tab-content__list--arrow"
  .tab-content__list--body
    .tab-content__list--body-text
      《5/25まで》5％ポイントバックのお得チケットをお持ちです
    .tab-content__list--body-time
      = fa_icon "clock-o", class: "tab-content__icon--time"
      %span
        19時間前
= link_to "" , class: "tab-content__list"  do
  = image_tag("https://static.mercdn.net/images/mercari_profile.png", width: "48", class: "tab-content__list--mercari")
  = fa_icon "angle-right", class: "tab-content__list--arrow"
  .tab-content__list--body
    .tab-content__list--body-text
      他のお客様より出品中の商品にいいねが付きました。
    .tab-content__list--body-time
      = fa_icon "clock-o", class: "tab-content__icon--time"
      %span
        5日前
//リストがある場合に最後に下記のリストを表示させる必要がある。(メルカリはリスト5個のあとに下記の一覧を見るリストが表示)
%li.tab-content__list
  = link_to "一覧を見る" , "/" , class: "tab-content__list--link"