config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'items#index'

  resources :items do
    member do
      get :buy
      post :pay
      get :purchase
      get :look
    end
  end

  resources :users do
    member do
      get :signout
      get :listing
    end
  end

  resources :credits do
    collection do
      get 'index'
      get 'complete', to: 'credits#complete'
      post 'payment', to: 'credits#payment'
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController

  require "payjp"

  def new
    @user = current_user
    card = Credit.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def index
    @user = current_user
  end

  def payment
  end

  def complete
    card = Credit.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Credit.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
  @user = current_user
  card = Credit.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/views/credits/complete.html.haml
.item__container
  =render 'shared/header-logo'
%section.pickup-container
  %main.item__container__main
    %section.item__container__main__box
      %h2.item__box__header 支払い方法
      .credit__container-index
        %section
          %h3.credit__container-index-content クレジットカード一覧
        %section.user__card
          %input{:checked => "", :name => "card_sequence_no", :type => "radio", :value => "BmjS5JHZpKahU9eCRra6JWcc"}/
          .user__card-btn
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        %section.add__card
          .add__card-bottun
            = link_to new_credit_path, class: "add__card-btn-default" do
              次へ進む


  = render 'shared/footer-logo'

app/views/credits/index.html.haml
.main_header
  = render 'shared/header'
  - breadcrumb :user_card
  = breadcrumbs pretext: " ", separator: " › "
%section.pickup-container
  .mypage-body.clearfix
    = render 'shared/user-side'

    .credit__container
      %h2.chapter__header 支払い方法
      .credit__container-index
        %section
          %h3.credit__container-index-content クレジットカード一覧
        %section.add__card
          .add__card-btn
            = link_to new_credit_path, class: "add__card-btn-default" do
              = fa_icon "credit-card"
              クレジットカードを追加する
        %section
          = link_to '/', class: "payment__box-content" do
            %span 支払い方法について
            = fa_icon "angle-right"

  = render 'shared/footer'
  = render 'shared/sell-button'

app/views/credits/new.html.haml
.main_header
  = render 'shared/header'
  - breadcrumb :user_card
  = breadcrumbs pretext: " ", separator: " › "
%section.pickup-container
  .mypage-body.clearfix
    = render 'shared/user-side'
    .credit__registration
      %h2.chapter__header クレジットカード情報入力
      = render 'shared/credit'

  = render 'shared/footer'
  = render 'shared/sell-button'

app/views/credits/payment.html.haml
.item__container
  =render 'shared/header-logo'
%section.pickup-container
  %main.item__container__main
    %section.item__container__main__box
      %h2.item__box__header 支払い方法
      = render 'shared/credit'

  = render 'shared/footer-logo'

app/views/credits/show.html.haml
.main_header
  = render 'shared/header'
  - breadcrumb :user_card
  = breadcrumbs pretext: " ", separator: " › "
%section.pickup-container
  .mypage-body.clearfix
    = render 'shared/user-side'

    .credit__container
      %h2.chapter__header 支払い方法
      .credit__container-index
        %section
          %h3.credit__container-index-content クレジットカード一覧
        %section.user__card
          = form_tag( delete_credits_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
            %button.delete 削除する
          .user__card-btn
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        %section
          = link_to '/', class: "payment__box-content" do
            %span 支払い方法について
            = fa_icon "angle-right"

  = render 'shared/footer'
  = render 'shared/sell-button'