config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'items#index'

  resources :items do
    member do
      get :buy
      post :pay
      get :purchase
      get :look
    end
  end

  resources :users do
    member do
      get :signout
      get :listing
    end
  end

  resources :credits do
    collection do
      get 'index'
      get 'complete', to: 'credits#complete'
      post 'payment', to: 'credits#payment'
      post 'show', to: 'credits#show'
      post 'pay', to: 'credits#pay'
      post 'delete', to: 'credits#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :brand, optional: true
  belongs_to :category
  has_many :item_images, dependent: :destroy, inverse_of: :item
  # itemに紐づくcategory,brandが変更されたらそのテーブルも更新
  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :brand
  # itemレコードが削除されたらそのimageも削除
  accepts_nested_attributes_for :item_images, allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!,except:[:index,:show]
  before_action :set_item,only:[:show,:look,:edit,:update,:destroy, :purchase, :buy, :pay]

  require 'payjp'

  def index
    @items = Item.includes(:item_images).limit(4).order("created_at DESC")
    @category1 = Category.find(1)
    @category2 = Category.find(2)
    @category3 = Category.find(3)
    @brand1 = Brand.find(1)
  end

  def new
    @item = Item.new
    @item.item_images.build
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to root_path
  end

  def buy
   card = Credit.where(user_id: current_user.id).first
    #テーブルからpayjpの顧客IDを検索
    if card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "credits",action: "new"
    else
      Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def purchase
  end

  def show
    @category1 = Category.find(1)
    @user_items = Item.where(user_id: @item.user_id).sample(6)
  end

  def look
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to look_item_path
  end

  def destroy
    if @item.user_id == current_user.id
      @item.destroy
    end
    redirect_to items_path
  end

  def pay
    card = Credit.where(user_id: current_user.id).first
    Payjp.api_key = 'sk_test_62a0e6d04e58fcfc575e196c'
    Payjp::Charge.create(
    :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    :customer => card.customer_id, #顧客ID
    :currency => 'jpy', #日本円
  )

  redirect_to purchase_item_path
  end

  private

  # 親要素itemの子要素であるitem_imageのパラメータをattributesで取得(1対多の関係)
  def item_params
    params.require(:item).permit(:name,:info,:category_id,:brand_id,:size,:status,:delivery_cost,:prefecture,:delivery_day,:price,item_images_attributes: [:image]).merge(user_id: current_user.id )
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/items/buy.html.haml
.item__container
  =render 'shared/header-logo'
%section.pickup-container
  %main.item__container__main
    %section.item__container__main__box
      %h2.item__box__header 購入を確定しますか？
      %section.item__box__inner
        .item__box__list
          %h3.item-image
            = image_tag( @item.item_images[0].image , alt: "" , class: "show-item-box__image")
          %P.item-name
            = @item.name
          %div
            .price-box
              %p.item-price
                = number_to_currency( "#{@item.price}", locale: 'jp')
              %p.item-fee 送料込み
            .item-point
              ポイントはありません
            %ul.item-price-table
              .buy-price-call 支払い金額
              .buy-price-pay
                = number_to_currency( "#{@item.price}", locale: 'jp')
              %p.has-error-text 配送先と支払い方法の入力を完了してください。
              %label.payjp__btn
                購入する
                = form_tag(action: :pay, method: :post) do
                  %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "購入する" ,"data-key" => "pk_test_7d6421811945dc71ee2edf87"}

      %section.user__info
        .buy-container-inner
          %h3.delivery 配送先
          %p.adress-user-info
            〒150-0043
            %br
            東京都渋谷区道玄坂２丁目２３−１２
            %br
            ユーザーネーム
          %a.buy-user-info-fix{href: "/"}変更する >
      %section.user__footer
        .buy-footer-inner
          %h3.payment 支払い方法
          - if @default_card_information.blank?
            %br /
          - else
            = "**** **** **** " + @default_card_information.last4
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          = link_to complete_credits_path do
            .buy-user-info-fix
              変更する >


  = render 'shared/footer-logo'

app/views/items/edit.html.haml
= render 'shared/mercari-header'
%main.single-container
  %section.single-container__main
    %h2.item__header 商品の情報を入力
    / railsのバージョンが5.1以上の場合はform_with ↓ を使う
    /  = form_with model: @item do |f|
    = form_for @item do |f|
      .item__upload
        .item__upload__header
          出品画像
          %span.form-require 必須
        %p 最大10枚までアップロードできます
        .item__dropbox
        .item__dropbox__zone
          .item__dropbox__items-figure-edit
            = image_tag( @item.item_images[0].image , size: "138" , class: "itemimage")
          %a.item__dropbox__items-btn.edit
            %p 編集
          %a.item__dropbox__items-btn.delete
            %p 削除
          / / imageモデルに紐づくformタグを作成（ブロック引数はimage)
          / =f.fields_for :item_images, ItemImage.new do |image|
          /   %ul.item__dropbox__items
          /   .item__dropbox__uploader
          /   / formタグのラベル作成 itemではなくitem_imagesのテーブルに保存するためdoでpostする
          /   = image.label :image, for: "goods_image" , class: "item__dropbox__uploader-container" do
          /     =image.file_field :image ,id:"goods_image" , class: "goods_images hidden"
          / %pre.item__upload--visible
          /   ドラッグアンドドロップ
          /   またはクリックしてファイルをアップロード
      .item__content
        .form__group
          =f.label :商品名
          %span.form-require 必須
          = f.text_field :name, class: "input__default", placeholder: "商品名（必須 40文字まで)"
        .form__group
          =f.label :商品の説明
          %span.form-require 必須
          =f.text_area :info, class: "textarea__default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
      .item__content
        .item__content__header 商品の詳細
        .item__form__box
          .form__group
            =f.label :カテゴリー
            %span.form-require 必須
            / dbから持ってきたデータをselectするためのformパーツ（idで紐づけ）
            = f.collection_select :category_id, Category.all, :id, :name, {prompt: "---"},class: "input__default"
          .form__group
            =f.label :ブランド
            %span.form-require 必須
            = f.collection_select :brand_id, Brand.all, :id, :name, {prompt: "---"},class: "input__default"
          .form__group
            =f.label :サイズ
            %span.form-require 必須
            = f.select :size , ["S","M","L"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            =f.label :商品の状態
            %span.form-require 必須
            = f.select :status , ["新品,未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"] ,{ prompt: "---"} , {class: "input__default" }
      .item__content
        .item__content__header 配送について
        = link_to '?', "https://www.mercari.com/jp/help_center/article/68/",class: "form__question"
        .item__form__box
          .form__group
            %label
              配送料の負担
              %span.form-require 必須
            =f.select :delivery_cost , ["送料負担(出品者負担)","着払い(購入者負担)"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            %label
              発送元の地域
              %span.form-require 必須
            =f.select :prefecture , ["千葉県","東京都"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            %label
              発送までの日数
              %span.form-require 必須
            =f.select :delivery_day , ["1~2日で発送","2~3日で発送","4~7日で発送"] ,{ prompt: "---"} , {class: "input__default" }
      .item__content.clearfix
        .item__content__header 販売価格(300〜9,999,999)
        = link_to '?', "https://www.mercari.com/jp/help_center/article/64/",class: "form__question"
        .item__form__box__price
          %ul.item__form__right
            %li.item__form__right-box
              = f.label :価格
              %span.form-require 必須
              .item__price
                =f.label :¥, class: "item__price-label"
                =f.text_field :price, maxlength: "7", placeholder: "例)300", class: "item__price--input"
            %li.item__form__right-box
              販売手数料(10%)
              .l-right#output -
            %li.item__form__right-box
              %label
                販売利益
              .l-right2 -
      .item__content
        %p.sell__btn__box
          = link_to '禁止されている出品', "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
          、
          = link_to '行為', "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
          を必ずご確認ください。
        %p.sell__btn__box
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '偽ブランドの販売', "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
          は犯罪であり処罰される可能性があります。
        %p.sell__btn__box
          また、出品をもちまして
          = link_to '加盟店規約', "https://www.mercari.com/jp/seller_terms/ "
          に同意したことになります。
        .item_content__bottom_btn
          =f.submit :編集する,class: "btn-default btn-red"
        = link_to 'もどる', root_path, class: "btn-default btn-gray"
= render 'shared/login-footer'

app/views/items/index.html.haml
.main_header
  =render partial: 'shared/header'
.main_header_carousel
  =render partial: 'shared/top-carousel'
%section.pickup-container
  =render partial: 'shared/body'
.main_footer
  =render partial: 'shared/footer'
  =render partial: 'shared/sell-button'

app/views/items/look.html.haml
.main_header
  = render 'shared/header'
.show-item
  %section.show-item-content.clear.clearfix
    .show-item-content__name
      =@item.name
    .show-item-content__profile
      .show-item-content__profile--img
        = image_tag( @item.item_images[0].image , alt: "" , class: "show-item-box__image")
    %table.show-item-content__profile--text
      %tr
        %th 出品者
        %td.e1
          = link_to "" do
            =@item.user.nickname
      %tr
        %th カテゴリー
        %td.e1
          = link_to "" do
            = @item.category.name

      %tr
        %th ブランド
        %td.e1
          - if @item.brand == nil
          - else
            = @item.brand.name

      -if @item.size ==""
      -else
        %tr
          %th 商品のサイズ
          %td
            = @item.size
      %tr
        %th 商品の状態
        %td
          / = @item.state_before_type_cast
          = @item.status
      %tr
        %th 配送料の負担
        %td
          = @item.delivery_cost
      / %tr
      /   %th 配送の方法
      /   %td
      /     = @item.delivery
      %tr
        %th 配送元地域
        %td.e1
          = link_to "" do
            = @item.prefecture
      %tr
        %th 発送日の目安
        %td
          = @item.delivery_day
    .show-item-content__price
      .price__box.clear.clearfix
        %p.price__box--total
          = number_to_currency( "#{@item.price}", locale: 'jp')
        %p.price__box--tax
          （税込み）
        %p.price__box--option
          = @item.delivery_cost
  .show-item-edit-box
    %ul.show-item-edit__button
      = link_to edit_item_path do
        %li.show-item-content__button-edit
          商品の編集
    %p.text_center
    or
    %ul.show-item-stop__button
      = link_to edit_item_path do
        %li.show-item-content__button-edit
          出品を一旦停止する
    %ul.show-item-stop__button
      = link_to item_path , method: :delete do
        %li.show-item-content__button-edit
          商品を削除する
  .show-item-detail-message
    .message-container
      %p.message-alert
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .message-content
        =form_for "" do |f|
          = f.text_area :comment, type: 'text', rows: 4 , class: 'message-content_text'
          = f.submit "コメントする", class:'message-content_button'
= render 'shared/footer'

app/views/items/new.html.haml
= render 'shared/mercari-header'
%main.single-container
  %section.single-container__main
    %h2.item__header 商品の情報を入力
    / railsのバージョンが5.1以上の場合はform_with ↓ を使う
    /  = form_with model: @item do |f|
    = form_for @item do |f|
      .item__upload
        .item__upload__header
          出品画像
          %span.form-require 必須
        %p 最大10枚までアップロードできます
        .item__dropbox
        .item__dropbox__zone
          / imageモデルに紐づくformタグを作成（ブロック引数はimage)
          =f.fields_for :item_images, ItemImage.new do |image|
            %ul.item__dropbox__items
            .item__dropbox__uploader
            / formタグのラベル作成 itemではなくitem_imagesのテーブルに保存するためdoでpostする
            = image.label :image, for: "goods_image" , class: "item__dropbox__uploader-container" do
              =image.file_field :image ,id:"goods_image" , class: "goods_images hidden"
          %pre.item__upload--visible
            ドラッグアンドドロップ
            またはクリックしてファイルをアップロード
      .item__content
        .form__group
          =f.label :商品名
          %span.form-require 必須
          = f.text_field :name, class: "input__default", placeholder: "商品名（必須 40文字まで)"
        .form__group
          =f.label :商品の説明
          %span.form-require 必須
          =f.text_area :info, class: "textarea__default", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
      .item__content
        .item__content__header 商品の詳細
        .item__form__box
          .form__group
            =f.label :カテゴリー
            %span.form-require 必須
            / dbから持ってきたデータをselectするためのformパーツ（idで紐づけ）
            = f.collection_select :category_id, Category.all, :id, :name, {prompt: "---"},class: "input__default"
          .form__group
            =f.label :ブランド
            %span.form-not-require 任意
            = f.collection_select :brand_id, Brand.all, :id, :name, {prompt: "---"},class: "input__default"
          .form__group
            =f.label :サイズ
            %span.form-require 必須
            = f.select :size , ["S","M","L"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            =f.label :商品の状態
            %span.form-require 必須
            = f.select :status , ["新品,未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"] ,{ prompt: "---"} , {class: "input__default" }
      .item__content
        .item__content__header 配送について
        = link_to '?', "https://www.mercari.com/jp/help_center/article/68/",class: "form__question"
        .item__form__box
          .form__group
            %label
              配送料の負担
              %span.form-require 必須
            =f.select :delivery_cost , ["送料負担(出品者負担)","着払い(購入者負担)"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            %label
              発送元の地域
              %span.form-require 必須
            =f.select :prefecture , ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"] ,{ prompt: "---"} , {class: "input__default" }
          .form__group
            %label
              発送までの日数
              %span.form-require 必須
            =f.select :delivery_day , ["1~2日で発送","2~3日で発送","4~7日で発送"] ,{ prompt: "---"} , {class: "input__default" }
      .item__content.clearfix
        .item__content__header 販売価格(300〜9,999,999)
        = link_to '?', "https://www.mercari.com/jp/help_center/article/64/",class: "form__question"
        .item__form__box__price
          %ul.item__form__right
            %li.item__form__right-box
              = f.label :価格
              %span.form-require 必須
              .item__price
                =f.label :¥, class: "item__price-label"
                =f.text_field :price, maxlength: "7", placeholder: "例)300", class: "item__price--input"
            %li.item__form__right-box
              販売手数料(10%)
              .l-right#output -
            %li.item__form__right-box
              %label
                販売利益
              .l-right2 -
      .item__content
        %p.sell__btn__box
          = link_to '禁止されている出品', "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
          、
          = link_to '行為', "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
          を必ずご確認ください。
        %p.sell__btn__box
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          = link_to '偽ブランドの販売', "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
          は犯罪であり処罰される可能性があります。
        %p.sell__btn__box
          また、出品をもちまして
          = link_to '加盟店規約', "https://www.mercari.com/jp/seller_terms/ "
          に同意したことになります。
        .item_content__bottom_btn
          =f.submit :出品する,class: "btn-default btn-red"
        = link_to 'もどる', root_path, class: "btn-default btn-gray"
= render 'shared/login-footer'

app/views/items/purchase.html.haml
.item__container
  =render 'shared/header-logo'
%section.pickup-container
  %main.item__container__main
    %section.item__container__main__box
      %h2.item__box__header 購入が完了しました
      %section.item__box__inner
        .item__box__list
          %h3.item-image
            = image_tag( @item.item_images[0].image , alt: "" , class: "show-item-box__image")
          %P.item-name
            = @item.name
          %div
            .price-box
              %p.item-price
                = number_to_currency( "#{@item.price}", locale: 'jp')
              %p.item-fee 送料込み

      %section.user__info
        .buy-container-inner
          %h3.delivery 配送先
          %p.adress-user-info
            〒150-0043
            %br
            東京都渋谷区道玄坂２丁目２３−１２ フォンティスビル7F
            %br
            TECH-EXPERT ライフコーチ 横倉様

  = render 'shared/footer-logo'

app/views/items/show.html.haml
.main_header
  =render partial: 'shared/header'
.show-item
  %section.show-item-content.clear.clearfix
    .show-item-content__name
      =@item.name
    .show-item-content__profile
      .show-item-content__profile--img
        = image_tag( @item.item_images[0].image , alt: "" , class: "show-item-box__image")
    %table.show-item-content__profile--text
      %tr
        %th 出品者
        %td.e1
          = link_to "" do
            =@item.user.nickname
      %tr
        %th カテゴリー
        %td.e1
          = link_to "" do
            = @item.category.name

      %tr
        %th ブランド
        %td.e1
          - if @item.brand == nil
          - else
            = @item.brand.name

      -if @item.size ==""
      -else
        %tr
          %th 商品のサイズ
          %td
            = @item.size
      %tr
        %th 商品の状態
        %td
          / = @item.state_before_type_cast
          = @item.status
      %tr
        %th 配送料の負担
        %td
          = @item.delivery_cost
      / %tr
      /   %th 配送の方法
      /   %td
      /     = @item.delivery
      %tr
        %th 配送元地域
        %td.e1
          = link_to "" do
            = @item.prefecture
      %tr
        %th 発送日の目安
        %td
          = @item.delivery_day
    .show-item-content__price
      .price__box.clear.clearfix
        %p.price__box--total
          = number_to_currency( "#{@item.price}", locale: 'jp')
        %p.price__box--tax
          （税込み）
        %p.price__box--option
          = @item.delivery_cost
    %ul.show-item-content__button
      = link_to buy_item_path do
        %li.show-item-content__button-buy
          購入画面に進む
    .show-item-content__information
      .show-item-content__information--text
        = @item.info
    .show-item-button
      .show-item-button_left.clear.clearfix
        %li.show-item_icon
          = fa_icon "heart", type: :regular, class: "show-item_icon_like"
          %span
            いいね! 5
        %li.show-item_icon
          = fa_icon " flag ", class: "show-item_icon_report"
          %span
            不適切な商品の報告
      .show-item-button_right
        = link_to "https://www.mercari.com/jp/safe/description/" do
          .show-item_icon_safety
            = fa_icon " lock ", class: "show-item_icon_safety"
            %span
              あんしん・あんぜんへの取り組み
  .show-item-detail-message
    .message-container
      %p.message-alert
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .message-content
        =form_for "" do |f|
          = f.text_area :comment, type: 'text', rows: 4 , class: 'message-content_text'
          = f.submit "コメントする", class:'message-content_button'
  %nav.show-item__nav.clear.clearfix
    -if Item.exists?(id: @item.id - 1)
      = link_to "< 前の出品商品" , item_path(id: (@item.id-1)) , class: "show-item__nav--before"
    -if Item.exists?(id: @item.id + 1)
      = link_to "次の出品商品 >" , item_path(id: (@item.id+1)) , class: "show-item__nav--after"
  .show-item-social-media-box
    = link_to "/" , class: "social-media-box--facebook" do
      %i.fab.fa-facebook-square.fa-3x
    = link_to "/" , class: "social-media-box--twitter" do
      %i.fab.fa-twitter-square.fa-3x
    = link_to "/" , class: "social-media-box--pinterest" do
      %i.fab.fa-pinterest-square.fa-3x
  .show-item__box.clear.clearfix
    %ul.show-item__box-name
      %li
        = link_to "#{@item.user.nickname}さんの出品商品" , "/"
    - @user_items.each do |item|
      %ul.show-item__box-list
        = link_to "/items/#{item.id}" do
          %figure.item-box__figure
            / 商品の一枚目の写真を表示
            = image_tag item.item_images[0].image, alt: "",class: "item-box__image"
          .item-box__body
            .item-box__text
              .show-item__box__name
                =item.name
            .item-box__num
              .item-box__num__price
                = number_to_currency( "#{item.price}", locale: 'jp')
                .nice
                  = fa_icon "heart", type: :regular, class: "icon-like-border"
                  %span
                    1
              %p.item-box__num__price-tax
                (税込)
.main_footer
  =render partial: 'shared/footer'